/**
 * This file was generated by flotiq-api-typegen command
 * Generated at: 2025-04-16T10:52:43.530Z
 */

import {
  DataLink,
  ApiRequest,
  BaseObject,
  SearchParams,
  HydratedSearchResponse,
  InternalGeneratedForms,
  InternalGeneratedFormsHydrated,
  InternalGeneratedFormsHydratedTwice,
  InternalMedia,
  InternalMediaHydrated,
  InternalMediaHydratedTwice,
  InternalPluginSettings,
  InternalPluginSettingsHydrated,
  InternalPluginSettingsHydratedTwice,
  InternalTag,
  InternalTagHydrated,
  InternalTagHydratedTwice,
  InternalWebhooks,
  InternalWebhooksHydrated,
  InternalWebhooksHydratedTwice,
} from "@flotiq/flotiq-api-sdk";

type StringWithAutocomplete<T> = T | (string & Record<never, never>);

declare module "@flotiq/flotiq-api-sdk" {
  export type AnySpaceCTD =
    | About
    | Contact
    | ContactForm
    | Project
    | InternalGeneratedForms
    | InternalMedia
    | InternalPluginSettings
    | InternalTag
    | InternalWebhooks;

  export type AnySpaceCTDHydrated =
    | AboutHydrated
    | ContactHydrated
    | ContactFormHydrated
    | ProjectHydrated
    | InternalGeneratedFormsHydrated
    | InternalMediaHydrated
    | InternalPluginSettingsHydrated
    | InternalTagHydrated
    | InternalWebhooksHydrated;

  export type AnySpaceCTDHydratedTwice =
    | AboutHydratedTwice
    | ContactHydratedTwice
    | ContactFormHydratedTwice
    | ProjectHydratedTwice
    | InternalGeneratedFormsHydratedTwice
    | InternalMediaHydratedTwice
    | InternalPluginSettingsHydratedTwice
    | InternalTagHydratedTwice
    | InternalWebhooksHydratedTwice;

  // #region about

  export interface AboutBase extends BaseObject<"about"> {
    name?: string;
    description?: string;
    story_title?: string;
    story?: string;
    story_image?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>;
    mission_title?: string;
    mission_description?: string;
    mission_item?: Array<About.MissionItemBase>;
    team_title?: string;
    team_description?: string;
    team?: Array<About.TeamBase>;
    journey_title?: string;
    journey?: Array<About.JourneyBase>;
    __translations?: Array<About._translationsBase>;
  }

  export interface About extends AboutBase {
    story_image?: Array<DataLink>;
    mission_item?: Array<About.MissionItem>;
    team?: Array<About.Team>;
    journey?: Array<About.Journey>;
    __translations?: Array<About._translations>;
  }

  export interface AboutHydrated extends AboutBase {
    story_image?: Array<InternalMedia>;
    mission_item?: Array<About.MissionItemHydrated>;
    team?: Array<About.TeamHydrated>;
    journey?: Array<About.JourneyHydrated>;
    __translations?: Array<About._translationsHydrated>;
  }

  export interface AboutHydratedTwice extends AboutBase {
    story_image?: Array<InternalMediaHydrated>;
    mission_item?: Array<About.MissionItemHydratedTwice>;
    team?: Array<About.TeamHydratedTwice>;
    journey?: Array<About.JourneyHydratedTwice>;
    __translations?: Array<About._translationsHydratedTwice>;
  }

  export namespace About {
    export type FilterableFields = StringWithAutocomplete<
      | "name"
      | "description"
      | "story_title"
      | "story"
      | "story_image"
      | "story_image[*].type"
      | "story_image[*].dataUrl"
      | "mission_title"
      | "mission_description"
      | "mission_item"
      | "team_title"
      | "team_description"
      | "team"
      | "journey_title"
      | "journey"
      | "__translations"
      | "mission_item[*].title"
      | "mission_item[*].description"
      | "team[*].name"
      | "team[*].position"
      | "team[*].image"
      | "team[*].image[*].type"
      | "team[*].image[*].dataUrl"
      | "journey[*].year"
      | "journey[*].title"
      | "journey[*].description"
      | "__translations[*].name"
      | "__translations[*].description"
      | "__translations[*].story_title"
      | "__translations[*].story"
      | "__translations[*].story_image"
      | "__translations[*].story_image[*].type"
      | "__translations[*].story_image[*].dataUrl"
      | "__translations[*].mission_title"
      | "__translations[*].mission_description"
      | "__translations[*].mission_item"
      | "__translations[*].team_title"
      | "__translations[*].team_description"
      | "__translations[*].team"
      | "__translations[*].journey_title"
      | "__translations[*].journey"
      | "__translations[*].__language"
      | "__translations[*].mission_item[*].title"
      | "__translations[*].mission_item[*].description"
      | "__translations[*].team[*].name"
      | "__translations[*].team[*].position"
      | "__translations[*].team[*].image"
      | "__translations[*].team[*].image[*].type"
      | "__translations[*].team[*].image[*].dataUrl"
      | "__translations[*].journey[*].year"
      | "__translations[*].journey[*].title"
      | "__translations[*].journey[*].description"
    >;

    // #region About.mission_item

    export interface MissionItemBase {
      title?: string;
      description?: string;
    }

    export interface MissionItem extends MissionItemBase {}

    export interface MissionItemHydrated extends MissionItemBase {}

    export interface MissionItemHydratedTwice extends MissionItemBase {}

    export namespace MissionItem {
      export type FilterableFields = StringWithAutocomplete<
        "title" | "description"
      >;
    }

    // #endregion

    // #region About.team

    export interface TeamBase {
      name?: string;
      position?: string;
      image?:
        | Array<DataLink>
        | Array<InternalMedia>
        | Array<InternalMediaHydrated>
        | Array<InternalMediaHydratedTwice>;
    }

    export interface Team extends TeamBase {
      image?: Array<DataLink>;
    }

    export interface TeamHydrated extends TeamBase {
      image?: Array<InternalMedia>;
    }

    export interface TeamHydratedTwice extends TeamBase {
      image?: Array<InternalMediaHydrated>;
    }

    export namespace Team {
      export type FilterableFields = StringWithAutocomplete<
        "name" | "position" | "image" | "image[*].type" | "image[*].dataUrl"
      >;
    }

    // #endregion

    // #region About.journey

    export interface JourneyBase {
      year?: number;
      title?: string;
      description?: string;
    }

    export interface Journey extends JourneyBase {}

    export interface JourneyHydrated extends JourneyBase {}

    export interface JourneyHydratedTwice extends JourneyBase {}

    export namespace Journey {
      export type FilterableFields = StringWithAutocomplete<
        "year" | "title" | "description"
      >;
    }

    // #endregion

    // #region About.__translations

    export interface _translationsBase {
      name?: string;
      description?: string;
      story_title?: string;
      story?: string;
      story_image?:
        | Array<DataLink>
        | Array<InternalMedia>
        | Array<InternalMediaHydrated>
        | Array<InternalMediaHydratedTwice>;
      mission_title?: string;
      mission_description?: string;
      mission_item?: Array<_translations.MissionItemBase>;
      team_title?: string;
      team_description?: string;
      team?: Array<_translations.TeamBase>;
      journey_title?: string;
      journey?: Array<_translations.JourneyBase>;
      __language: string;
    }

    export interface _translations extends _translationsBase {
      story_image?: Array<DataLink>;
      mission_item?: Array<_translations.MissionItem>;
      team?: Array<_translations.Team>;
      journey?: Array<_translations.Journey>;
    }

    export interface _translationsHydrated extends _translationsBase {
      story_image?: Array<InternalMedia>;
      mission_item?: Array<_translations.MissionItemHydrated>;
      team?: Array<_translations.TeamHydrated>;
      journey?: Array<_translations.JourneyHydrated>;
    }

    export interface _translationsHydratedTwice extends _translationsBase {
      story_image?: Array<InternalMediaHydrated>;
      mission_item?: Array<_translations.MissionItemHydratedTwice>;
      team?: Array<_translations.TeamHydratedTwice>;
      journey?: Array<_translations.JourneyHydratedTwice>;
    }

    export namespace _translations {
      export type FilterableFields = StringWithAutocomplete<
        | "name"
        | "description"
        | "story_title"
        | "story"
        | "story_image"
        | "story_image[*].type"
        | "story_image[*].dataUrl"
        | "mission_title"
        | "mission_description"
        | "mission_item"
        | "team_title"
        | "team_description"
        | "team"
        | "journey_title"
        | "journey"
        | "__language"
        | "mission_item[*].title"
        | "mission_item[*].description"
        | "team[*].name"
        | "team[*].position"
        | "team[*].image"
        | "team[*].image[*].type"
        | "team[*].image[*].dataUrl"
        | "journey[*].year"
        | "journey[*].title"
        | "journey[*].description"
      >;

      // #region About.__translations.mission_item

      export interface MissionItemBase {
        title?: string;
        description?: string;
      }

      export interface MissionItem extends MissionItemBase {}

      export interface MissionItemHydrated extends MissionItemBase {}

      export interface MissionItemHydratedTwice extends MissionItemBase {}

      export namespace MissionItem {
        export type FilterableFields = StringWithAutocomplete<
          "title" | "description"
        >;
      }

      // #endregion

      // #region About.__translations.team

      export interface TeamBase {
        name?: string;
        position?: string;
        image?:
          | Array<DataLink>
          | Array<InternalMedia>
          | Array<InternalMediaHydrated>
          | Array<InternalMediaHydratedTwice>;
      }

      export interface Team extends TeamBase {
        image?: Array<DataLink>;
      }

      export interface TeamHydrated extends TeamBase {
        image?: Array<InternalMedia>;
      }

      export interface TeamHydratedTwice extends TeamBase {
        image?: Array<InternalMediaHydrated>;
      }

      export namespace Team {
        export type FilterableFields = StringWithAutocomplete<
          "name" | "position" | "image" | "image[*].type" | "image[*].dataUrl"
        >;
      }

      // #endregion

      // #region About.__translations.journey

      export interface JourneyBase {
        year?: number;
        title?: string;
        description?: string;
      }

      export interface Journey extends JourneyBase {}

      export interface JourneyHydrated extends JourneyBase {}

      export interface JourneyHydratedTwice extends JourneyBase {}

      export namespace Journey {
        export type FilterableFields = StringWithAutocomplete<
          "year" | "title" | "description"
        >;
      }

      // #endregion
    }

    // #endregion
  }

  // #endregion

  // #region contact

  export interface ContactBase extends BaseObject<"contact"> {
    contact_title?: string;
    description?: string;
    get_in_touch_title?: string;
    get_in_touch_description?: string;
    address?: string;
    phone?: string;
    email?: string;
    business_hours_title?: string;
    business_hours?: Array<Contact.BusinessHoursBase>;
    send_a_message_title?: string;
    send_a_message_description?: string;
    __translations?: Array<Contact._translationsBase>;
  }

  export interface Contact extends ContactBase {
    business_hours?: Array<Contact.BusinessHours>;
    __translations?: Array<Contact._translations>;
  }

  export interface ContactHydrated extends ContactBase {
    business_hours?: Array<Contact.BusinessHoursHydrated>;
    __translations?: Array<Contact._translationsHydrated>;
  }

  export interface ContactHydratedTwice extends ContactBase {
    business_hours?: Array<Contact.BusinessHoursHydratedTwice>;
    __translations?: Array<Contact._translationsHydratedTwice>;
  }

  export namespace Contact {
    export type FilterableFields = StringWithAutocomplete<
      | "contact_title"
      | "description"
      | "get_in_touch_title"
      | "get_in_touch_description"
      | "address"
      | "phone"
      | "email"
      | "business_hours_title"
      | "business_hours"
      | "send_a_message_title"
      | "send_a_message_description"
      | "__translations"
      | "business_hours[*].day"
      | "business_hours[*].hours"
      | "__translations[*].contact_title"
      | "__translations[*].description"
      | "__translations[*].get_in_touch_title"
      | "__translations[*].get_in_touch_description"
      | "__translations[*].address"
      | "__translations[*].phone"
      | "__translations[*].email"
      | "__translations[*].business_hours_title"
      | "__translations[*].business_hours"
      | "__translations[*].send_a_message_title"
      | "__translations[*].send_a_message_description"
      | "__translations[*].__language"
      | "__translations[*].business_hours[*].day"
      | "__translations[*].business_hours[*].hours"
    >;

    // #region Contact.business_hours

    export interface BusinessHoursBase {
      day?: string;
      hours?: string;
    }

    export interface BusinessHours extends BusinessHoursBase {}

    export interface BusinessHoursHydrated extends BusinessHoursBase {}

    export interface BusinessHoursHydratedTwice extends BusinessHoursBase {}

    export namespace BusinessHours {
      export type FilterableFields = StringWithAutocomplete<"day" | "hours">;
    }

    // #endregion

    // #region Contact.__translations

    export interface _translationsBase {
      contact_title?: string;
      description?: string;
      get_in_touch_title?: string;
      get_in_touch_description?: string;
      address?: string;
      phone?: string;
      email?: string;
      business_hours_title?: string;
      business_hours?: Array<_translations.BusinessHoursBase>;
      send_a_message_title?: string;
      send_a_message_description?: string;
      __language: string;
    }

    export interface _translations extends _translationsBase {
      business_hours?: Array<_translations.BusinessHours>;
    }

    export interface _translationsHydrated extends _translationsBase {
      business_hours?: Array<_translations.BusinessHoursHydrated>;
    }

    export interface _translationsHydratedTwice extends _translationsBase {
      business_hours?: Array<_translations.BusinessHoursHydratedTwice>;
    }

    export namespace _translations {
      export type FilterableFields = StringWithAutocomplete<
        | "contact_title"
        | "description"
        | "get_in_touch_title"
        | "get_in_touch_description"
        | "address"
        | "phone"
        | "email"
        | "business_hours_title"
        | "business_hours"
        | "send_a_message_title"
        | "send_a_message_description"
        | "__language"
        | "business_hours[*].day"
        | "business_hours[*].hours"
      >;

      // #region Contact.__translations.business_hours

      export interface BusinessHoursBase {
        day?: string;
        hours?: string;
      }

      export interface BusinessHours extends BusinessHoursBase {}

      export interface BusinessHoursHydrated extends BusinessHoursBase {}

      export interface BusinessHoursHydratedTwice extends BusinessHoursBase {}

      export namespace BusinessHours {
        export type FilterableFields = StringWithAutocomplete<"day" | "hours">;
      }

      // #endregion
    }

    // #endregion
  }

  // #endregion

  // #region contact_form

  export interface ContactFormBase extends BaseObject<"contact_form"> {
    name: string;
    email: string;
    question?: string;
  }

  export interface ContactForm extends ContactFormBase {}

  export interface ContactFormHydrated extends ContactFormBase {}

  export interface ContactFormHydratedTwice extends ContactFormBase {}

  export namespace ContactForm {
    export type FilterableFields = StringWithAutocomplete<
      "name" | "email" | "question"
    >;
  }

  // #endregion

  // #region project

  export interface ProjectBase extends BaseObject<"project"> {
    name: string;
    slug: string;
    tags?:
      | Array<DataLink>
      | Array<InternalTag>
      | Array<InternalTagHydrated>
      | Array<InternalTagHydratedTwice>;
    short_description?: string;
    description?: string;
    headerImage?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>;
    gallery?:
      | Array<DataLink>
      | Array<InternalMedia>
      | Array<InternalMediaHydrated>
      | Array<InternalMediaHydratedTwice>;
    __translations?: Array<Project._translationsBase>;
  }

  export interface Project extends ProjectBase {
    tags?: Array<DataLink>;
    headerImage?: Array<DataLink>;
    gallery?: Array<DataLink>;
    __translations?: Array<Project._translations>;
  }

  export interface ProjectHydrated extends ProjectBase {
    tags?: Array<InternalTag>;
    headerImage?: Array<InternalMedia>;
    gallery?: Array<InternalMedia>;
    __translations?: Array<Project._translationsHydrated>;
  }

  export interface ProjectHydratedTwice extends ProjectBase {
    tags?: Array<InternalTagHydrated>;
    headerImage?: Array<InternalMediaHydrated>;
    gallery?: Array<InternalMediaHydrated>;
    __translations?: Array<Project._translationsHydratedTwice>;
  }

  export namespace Project {
    export type FilterableFields = StringWithAutocomplete<
      | "name"
      | "slug"
      | "tags"
      | "tags[*].type"
      | "tags[*].dataUrl"
      | "short_description"
      | "description"
      | "headerImage"
      | "headerImage[*].type"
      | "headerImage[*].dataUrl"
      | "gallery"
      | "gallery[*].type"
      | "gallery[*].dataUrl"
      | "__translations"
      | "__translations[*].name"
      | "__translations[*].slug"
      | "__translations[*].tags"
      | "__translations[*].tags[*].type"
      | "__translations[*].tags[*].dataUrl"
      | "__translations[*].short_description"
      | "__translations[*].description"
      | "__translations[*].headerImage"
      | "__translations[*].headerImage[*].type"
      | "__translations[*].headerImage[*].dataUrl"
      | "__translations[*].gallery"
      | "__translations[*].gallery[*].type"
      | "__translations[*].gallery[*].dataUrl"
      | "__translations[*].__language"
    >;

    // #region Project.__translations

    export interface _translationsBase {
      name: string;
      slug: string;
      tags?:
        | Array<DataLink>
        | Array<InternalTag>
        | Array<InternalTagHydrated>
        | Array<InternalTagHydratedTwice>;
      short_description?: string;
      description?: string;
      headerImage?:
        | Array<DataLink>
        | Array<InternalMedia>
        | Array<InternalMediaHydrated>
        | Array<InternalMediaHydratedTwice>;
      gallery?:
        | Array<DataLink>
        | Array<InternalMedia>
        | Array<InternalMediaHydrated>
        | Array<InternalMediaHydratedTwice>;
      __language: string;
    }

    export interface _translations extends _translationsBase {
      tags?: Array<DataLink>;
      headerImage?: Array<DataLink>;
      gallery?: Array<DataLink>;
    }

    export interface _translationsHydrated extends _translationsBase {
      tags?: Array<InternalTag>;
      headerImage?: Array<InternalMedia>;
      gallery?: Array<InternalMedia>;
    }

    export interface _translationsHydratedTwice extends _translationsBase {
      tags?: Array<InternalTagHydrated>;
      headerImage?: Array<InternalMediaHydrated>;
      gallery?: Array<InternalMediaHydrated>;
    }

    export namespace _translations {
      export type FilterableFields = StringWithAutocomplete<
        | "name"
        | "slug"
        | "tags"
        | "tags[*].type"
        | "tags[*].dataUrl"
        | "short_description"
        | "description"
        | "headerImage"
        | "headerImage[*].type"
        | "headerImage[*].dataUrl"
        | "gallery"
        | "gallery[*].type"
        | "gallery[*].dataUrl"
        | "__language"
      >;
    }

    // #endregion
  }

  // #endregion

  export interface FlotiqObjectAPI {
    about: ApiRequest<
      About,
      AboutHydrated,
      AboutHydratedTwice,
      About.FilterableFields
    >;

    contact: ApiRequest<
      Contact,
      ContactHydrated,
      ContactHydratedTwice,
      Contact.FilterableFields
    >;

    contact_form: ApiRequest<
      ContactForm,
      ContactFormHydrated,
      ContactFormHydratedTwice,
      ContactForm.FilterableFields
    >;

    project: ApiRequest<
      Project,
      ProjectHydrated,
      ProjectHydratedTwice,
      Project.FilterableFields
    >;

    _generated_forms: ApiRequest<
      InternalGeneratedForms,
      InternalGeneratedFormsHydrated,
      InternalGeneratedFormsHydratedTwice,
      InternalGeneratedForms.FilterableFields
    >;

    _media: ApiRequest<
      InternalMedia,
      InternalMediaHydrated,
      InternalMediaHydratedTwice,
      InternalMedia.FilterableFields
    >;

    _plugin_settings: ApiRequest<
      InternalPluginSettings,
      InternalPluginSettingsHydrated,
      InternalPluginSettingsHydratedTwice,
      InternalPluginSettings.FilterableFields
    >;

    _tag: ApiRequest<
      InternalTag,
      InternalTagHydrated,
      InternalTagHydratedTwice,
      InternalTag.FilterableFields
    >;

    _webhooks: ApiRequest<
      InternalWebhooks,
      InternalWebhooksHydrated,
      InternalWebhooksHydratedTwice,
      InternalWebhooks.FilterableFields
    >;
  }

  export interface FlotiqSearchAPI {
    query<P extends SearchParams>(
      params?: P,
    ): Promise<
      HydratedSearchResponse<
        P,
        AnySpaceCTD,
        AnySpaceCTDHydrated,
        AnySpaceCTDHydratedTwice
      >
    >;
  }
}
