import type { Metadata } from 'next';
import { draftMode } from 'next/headers';
import '../globals.css';
import { ReactNode } from 'react';
import Navbar from '@/app/_components/Navbar/Navbar';
import Footer from '@/app/_components/Footer/Footer';
import { DraftModeInfo } from '../_components/DraftModeInfo/DraftModeInfo';
import NextTopLoader from 'nextjs-toploader';
import Script from 'next/script';
import { LivePreviewStatus } from '@flotiq/nextjs-live-preview/client';
import { livePreview } from '@flotiq/nextjs-live-preview/server';
import { ThemeProvider } from '@/app/_components/ThemeProvider/ThemeProvider';
import { content } from '@/flotiq-api-client';

export const metadata: Metadata = {
  title: 'Demo shop',
  description: 'Generated by create next app',
};

export async function generateStaticParams() {
  return [{ lang: 'en' }, { lang: 'pl' }];
}

export default async function RootLayout({
  children,
  params,
}: Readonly<{
  children: ReactNode;
  params: Promise<{ lang: string }>;
}>) {
  const { isEnabled } = await draftMode();
  const { isEnabled: isLivePreviewEnabled } = await livePreview();
  const { lang } = await params;
  const list = await content._generated_forms.list({
    limit: 1,
    filters: { CTDslug: { filter: 'contact_form', type: 'equals' } },
  });
  const generatedFormData = list.data?.[0];

  return (
    <html lang={lang} className="scroll-smooth">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {isLivePreviewEnabled ? (
            <LivePreviewStatus
              editorKey={process.env.FLOTIQ_EDITOR_KEY || ''}
            />
          ) : null}
          <Navbar lang={lang} />
          <NextTopLoader
            color="#0083FC"
            height={4}
            shadow=""
            template='<div class="bar shadow-[0_3px_5px_#015bd7a1,_0_0_0px_#015bd78f]" role="bar">'
            zIndex={100}
          />
          {isEnabled ? (
            <DraftModeInfo editorKey={process.env.FLOTIQ_EDITOR_KEY || ''} />
          ) : null}

          <main className="container mx-auto flex-1 px-4 py-8">{children}</main>
          <Footer lang={lang} />
        </ThemeProvider>
        {generatedFormData && <Script src={generatedFormData.formUrl} async />}
      </body>
    </html>
  );
}
